version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: "backend"
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./backend:/usr/src/app
